# Generated by Django 5.2.15 on 2026-06-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان گواهینامه / دوره')),
                ('issuer', models.CharField(max_length=200, verbose_name='موسسه صادرکننده')),
                ('issue_date', models.DateField(verbose_name='تاریخ اخذ')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='candidates.candidate', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'گواهینامه متقاضی',
                'verbose_name_plural': 'گواهینامه\u200cهای متقاضی',
            },
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام زبان')),
                ('proficiency', models.CharField(choices=[('ELEMENTARY', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته'), ('NATIVE', 'زبان مادری')], default='INTERMEDIATE', max_length=20, verbose_name='سطح تسلط')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidates.candidate', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'زبان متقاضی',
                'verbose_name_plural': 'زبان\u200cهای متقاضی',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('level', models.CharField(choices=[('BEGINNER', 'مبتدی'), ('INTERMEDIATE', 'متوسط'), ('EXPERT', 'متخصص')], default='INTERMEDIATE', max_length=20, verbose_name='سطح مهارت')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidate', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'مهارت متقاضی',
                'verbose_name_plural': 'مهارت\u200cهای متقاضی',
            },
        ),
    ]
