# Generated by Django 5.2.15 on 2026-06-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_interviewerscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstagestate',
            name='score_discrepancy_alert',
            field=models.BooleanField(default=False, verbose_name='هشدار اختلاف فاحش نمرات'),
        ),
    ]
