# Generated by Django 5.2.15 on 2026-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_applicationstagestate_evaluation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstagestate',
            name='is_conditional_pass',
            field=models.BooleanField(default=False, verbose_name='قبول ارفاقی / ارجاع مشروط'),
        ),
    ]
