# Generated by Django 5.2.15 on 2026-06-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_jobapplication_admission_date'),
        ('jobs', '0017_alter_jobopportunity_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInterviewerCompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('score', models.FloatField(default=0.0, verbose_name='نمره')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_given_scores', to='jobs.assessmentcompetency', verbose_name='شایستگی/پارامتر')),
                ('external_interviewer_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='candidates.externalinterviewerscore', verbose_name='نمره مصاحبه\u200cگر خارجی')),
            ],
            options={
                'verbose_name': 'نمره پارامتر مصاحبه\u200cگر خارجی',
                'verbose_name_plural': 'نمرات پارامترهای مصاحبه\u200cگران خارجی',
                'unique_together': {('external_interviewer_score', 'competency')},
            },
        ),
    ]
