# Generated by Django 5.2.15 on 2026-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_applicationstagestate_evaluation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('notification_type', models.CharField(choices=[('SMS', 'پیامک'), ('EMAIL', 'ایمیل')], max_length=10, verbose_name='نوع اعلان')),
                ('recipient', models.CharField(max_length=255, verbose_name='گیرنده')),
                ('subject', models.CharField(max_length=255, verbose_name='عنوان / موضوع')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('SENT', 'ارسال شده'), ('FAILED', 'خطا در ارسال')], default='SENT', max_length=10, verbose_name='وضعیت ارسال')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='متن خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'لاگ اعلان',
                'verbose_name_plural': 'لاگ\u200cهای اعلانات',
                'ordering': ['-created_at'],
            },
        ),
    ]
