# Generated by Django 5.2.16 on 2026-07-22 13:51

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[apps.core.validators.validate_resume_file_size, apps.core.validators.validate_resume_file_extension], verbose_name='فایل رزومه'),
        ),
    ]
