# Generated by Django 5.2.16 on 2026-07-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_alter_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='screening_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت نتیجه غربالگری'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نتیجه غربالگری'),
        ),
    ]
