# Generated by Django 5.2.15 on 2026-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('RECRUITMENT_DIRECTOR', 'مدیر کل جذب و استخدام'), ('RECRUITMENT_SPECIALIST', 'کارشناس جذب و استخدام'), ('DEPARTMENT_USER', 'کاربر دپارتمان'), ('JOB_CLASSIFICATION_USER', 'کاربر طبقه\u200cبندی مشاغل'), ('INTERVIEWER', 'مصاحبه\u200cگر'), ('EXTERNAL_ASSESSOR', 'ارزیاب خارجی'), ('READ_ONLY_AUDITOR', 'حسابرس فقط\u200cخواندنی'), ('ADMIN', 'مدیر سیستم'), ('CANDIDATE', 'متقاضی')], default='INTERVIEWER', max_length=30, verbose_name='نقش'),
        ),
    ]
