# Generated by Django 5.2.15 on 2026-06-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_smstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_family',
            field=models.CharField(choices=[('vazir', 'وزیرمتن'), ('yekan', 'یکان\u200cبخش'), ('shabnam', 'شبنم'), ('samim', 'صمیم')], default='vazir', max_length=20, verbose_name='فونت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'کوچک'), ('medium', 'متوسط (پیش\u200cفرض)'), ('large', 'بزرگ'), ('xlarge', 'خیلی بزرگ')], default='medium', max_length=20, verbose_name='اندازه قلم'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('indigo', 'غروب ایندیگو (پیش\u200cفرض)'), ('emerald', 'سبز زمردین'), ('slate', 'سنگ لوح تیره (سنگین)'), ('sunset', 'آفتاب سوزان'), ('crimson', 'سرخ یاقوتی')], default='indigo', max_length=20, verbose_name='پوسته رنگی'),
        ),
    ]
