# Generated by Django 5.2.16 on 2026-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_planning', '0003_jobstageplan_is_exact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetypeconfiguration',
            name='default_sla_days',
            field=models.PositiveIntegerField(default=5, verbose_name='مهلت استاندارد انجام (روز کاری)'),
        ),
    ]
