# Generated by Django 5.2.15 on 2026-06-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobopportunity_weight_assessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام الگو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات الگو')),
            ],
            options={
                'verbose_name': 'الگوی فرآیند استخدام',
                'verbose_name_plural': 'الگوهای فرآیند استخدام',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='EvaluationStage',
            new_name='JobOpportunityStage',
        ),
        migrations.AlterModelOptions(
            name='jobopportunitystage',
            options={'ordering': ['sequence', 'created_at'], 'verbose_name': 'مرحله ارزیابی فرصت شغلی', 'verbose_name_plural': 'مراحل ارزیابی فرصت\u200cهای شغلی'},
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='assigned_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس جذب مسئول'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='headcount',
            field=models.PositiveIntegerField(default=1, verbose_name='ظرفیت جذب (تعداد)'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای داخلی'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='recruitment_type',
            field=models.CharField(choices=[('INTERNAL', 'داخلی'), ('EXTERNAL', 'خارجی'), ('TRANSFER', 'انتقالی'), ('CONTRACTUAL', 'قراردادی / پروژه\u200cای')], default='EXTERNAL', max_length=20, verbose_name='نوع استخدام'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='request_number',
            field=models.CharField(default='TEMP-REQ', max_length=50, unique=True, verbose_name='شماره درخواست'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='واحد سازمانی'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='department',
            field=models.CharField(max_length=100, verbose_name='بخش / دپارتمان'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'دریافت شده'), ('PLANNING', 'برنامه\u200cریزی'), ('PUBLISHED', 'منتشر شده'), ('REGISTRATION_CLOSED', 'خاتمه ثبت\u200cنام'), ('SCREENING', 'غربالگری اولیه'), ('EXAM', 'آزمون کتبی'), ('INTERVIEW', 'مصاحبه حضوری'), ('ASSESSMENT', 'کانون ارزیابی'), ('FINAL_SELECTION', 'انتخاب نهایی'), ('CLOSED', 'بسته\u200cشده'), ('CANCELLED', 'لغو شده')], default='RECEIVED', max_length=30, verbose_name='وضعیت فرصت شغلی'),
        ),
        migrations.CreateModel(
            name='WorkflowStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله پیش\u200cفرض')),
                ('default_weight', models.PositiveIntegerField(default=0, verbose_name='وزن پیش\u200cفرض (٪)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.workflowtemplate', verbose_name='الگوی فرآیند')),
            ],
            options={
                'verbose_name': 'مرحله پیش\u200cفرض فرآیند',
                'verbose_name_plural': 'مراحل پیش\u200cفرض فرآیند',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.workflowtemplate', verbose_name='الگوی فرآیند استخدامی'),
        ),
    ]
