# Generated by Django 5.2.15 on 2026-06-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobopportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='job_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='رده شغلی'),
        ),
    ]
