# Generated by Django 5.2.15 on 2026-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobopportunity_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='job_category',
            field=models.CharField(blank=True, choices=[('اپراتور - تعمیرکار', 'اپراتور - تعمیرکار'), ('کاردان', 'کاردان'), ('کاردان مسئول', 'کاردان مسئول'), ('کارشناس', 'کارشناس'), ('کارشناس مسئول', 'کارشناس مسئول'), ('کارشناس مدیریت', 'کارشناس مدیریت')], max_length=100, null=True, verbose_name='رده شغلی'),
        ),
    ]
