# Generated by Django 5.2.15 on 2026-06-20 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobopportunitystage_is_manually_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد شغل'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='request_number',
            field=models.CharField(max_length=50, verbose_name='شماره درخواست'),
        ),
        migrations.AddConstraint(
            model_name='jobopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request_number',), name='unique_request_number_active', violation_error_message='یک فرصت شغلی فعال با این شماره درخواست از قبل وجود دارد.'),
        ),
        migrations.AddConstraint(
            model_name='jobopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_code_active', violation_error_message='یک فرصت شغلی فعال با این کد شغل از قبل وجود دارد.'),
        ),
    ]
