# Generated by Django 5.2.15 on 2026-06-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_organizationsetting_exam_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='sms_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='کلید API / کلمه عبور پنل'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='sms_provider',
            field=models.CharField(choices=[('MOCK', 'شبیه\u200cساز (ثبت در فایل لاگ سیستم)'), ('KAVENEGAR', 'پنل کاوه نگار (Kavenegar)'), ('MELIPAYAMAK', 'پنل ملی پیامک (Melipayamak)')], default='MOCK', max_length=30, verbose_name='ارائه\u200cدهنده پنل پیامک'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='sms_sender_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='شماره خط اختصاصی فرستنده'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='آدرس سرور SMTP (مثال: smtp.gmail.com)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='کلمه عبور SMTP'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='پورت SMTP'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_sender_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل فرستنده پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='استفاده از SSL'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='استفاده از TLS'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نام کاربری SMTP (ایمیل)'),
        ),
    ]
