# Generated by Django 5.2.15 on 2026-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_organizationsetting_sms_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='email_provider',
            field=models.CharField(choices=[('CUSTOM', 'ایجاد دستی (SMTP سفارشی)'), ('GMAIL', 'گوگل (Gmail)'), ('OUTLOOK', 'اوتلوک (Outlook)')], default='CUSTOM', max_length=30, verbose_name='سرویس\u200cدهنده ایمیل'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='sms_custom_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس API اختصاصی / دستی'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='sms_provider',
            field=models.CharField(choices=[('MOCK', 'شبیه\u200cساز (ثبت در فایل لاگ سیستم)'), ('KAVENEGAR', 'پنل کاوه نگار (Kavenegar)'), ('MELIPAYAMAK', 'پنل ملی پیامک (Melipayamak)'), ('FARAPAYAMAK', 'پنل فراپیامک (Farapayamak)'), ('OTHER', 'سایر پیام\u200cرسان\u200cها (پیام\u200cرسان\u200cهای دیگر)'), ('CUSTOM', 'ایجاد دستی درگاه (تنظیم آدرس API اختصاصی)')], default='MOCK', max_length=30, verbose_name='ارائه\u200cدهنده پنل پیامک'),
        ),
    ]
