# Generated by Django 5.2.15 on 2026-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_competencymodel_jobopportunitycompetency_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='license_key',
            field=models.TextField(blank=True, default='', verbose_name='کلید لایسنس سیستم'),
        ),
    ]
