# Generated by Django 5.2.16 on 2026-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_organizationsetting_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='request_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='شماره درخواست'),
        ),
    ]
