# Generated by Django 5.2.16 on 2026-07-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_remove_unique_code_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='factory',
            field=models.CharField(choices=[('', '---------'), ('فولاد مبارکه', 'فولاد مبارکه'), ('مجتمع فولاد و نورد سبا', 'مجتمع فولاد و نورد سبا'), ('فولاد هرمزگان', 'فولاد هرمزگان'), ('فولاد امیرکبیر', 'فولاد امیرکبیر'), ('فولاد سفیددشت', 'فولاد سفیددشت'), ('فولاد سنگان', 'فولاد سنگان'), ('فولاد بافت', 'فولاد بافت'), ('فولاد غدیر نیریز', 'فولاد غدیر نیریز'), ('فولاد سیرجان', 'فولاد سیرجان'), ('آهن و فولاد گل گهر', 'آهن و فولاد گل گهر'), ('چادرملو', 'چادرملو'), ('فولاد خراسان', 'فولاد خراسان'), ('ذوب آهن اصفهان', 'ذوب آهن اصفهان'), ('غیره', 'غیره')], default='', max_length=100, verbose_name='کارخانه'),
        ),
    ]
