# Generated by Django 5.2.16 on 2026-07-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_add_factory_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='factory',
            field=models.CharField(blank=True, choices=[('', '---------'), ('فولاد مبارکه', 'فولاد مبارکه'), ('مجتمع فولاد و نورد سبا', 'مجتمع فولاد و نورد سبا'), ('فولاد هرمزگان', 'فولاد هرمزگان'), ('فولاد امیرکبیر', 'فولاد امیرکبیر'), ('فولاد سفیددشت', 'فولاد سفیددشت'), ('فولاد سنگان', 'فولاد سنگان'), ('غیره', 'غیره')], default='', max_length=100, verbose_name='کارخانه'),
        ),
    ]
