# Generated by Django 5.2.16 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_factory_blank_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='assessment_referral_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ معرفی به کانون'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='assessment_result_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعلام نتیجه کانون'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='exam_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد آزمون'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='final_result_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعلام نتیجه نهایی'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='final_result_letter_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره نامه اعلام نتیجه نهایی'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='has_skill_exam',
            field=models.BooleanField(default=False, verbose_name='آزمون مهارتی دارد'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='has_written_exam',
            field=models.BooleanField(default=False, verbose_name='آزمون کتبی دارد'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='initial_meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ جلسه اولیه'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='interview_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مصاحبه'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='پایان ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='شروع ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='screening_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='پایان غربالگری'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='skill_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آزمون مهارتی'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='written_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آزمون کتبی'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='written_exam_result_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعلام نتایج کتبی'),
        ),
    ]
