# Generated by Django 5.2.16 on 2026-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_jobopportunity_assessment_referral_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='post_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پست'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='suggested_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مسیر پیشنهادی'),
        ),
    ]
