# Generated by Django 5.2.16 on 2026-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_jobopportunity_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره درخواست'),
        ),
    ]
