# Generated by Django 5.2.16 on 2026-07-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_alter_jobopportunity_request_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobopportunity',
            name='unique_request_number_active',
        ),
    ]
