# Generated by Django 5.2.15 on 2026-06-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0011_jobopportunitystage_stage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ روز تعطیل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مناسبت تعطیلی')),
            ],
            options={
                'verbose_name': 'روز تعطیل رسمی',
                'verbose_name_plural': 'روزهای تعطیل رسمی',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StageTypeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('stage_type', models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], max_length=20, unique=True, verbose_name='نوع مرحله')),
                ('default_sla_days', models.PositiveIntegerField(default=5, verbose_name='SLA پیش\u200cفرض (روز کاری)')),
                ('monthly_capacity', models.PositiveIntegerField(default=100, verbose_name='ظرفیت ماهانه (تعداد نفرات)')),
            ],
            options={
                'verbose_name': 'تنظیمات نوع مرحله',
                'verbose_name_plural': 'تنظیمات انواع مراحل',
            },
        ),
        migrations.CreateModel(
            name='JobRecruitmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع برنامه\u200cریزی')),
                ('predicted_end_date', models.DateField(verbose_name='تاریخ پیش\u200cبینی شده اتمام')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('COMPLETED', 'خاتمه یافته')], default='DRAFT', max_length=20, verbose_name='وضعیت برنامه')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_plan', to='jobs.jobopportunity', verbose_name='فرصت شغلی')),
            ],
            options={
                'verbose_name': 'برنامه جذب شغل',
                'verbose_name_plural': 'برنامه\u200cهای جذب مشاغل',
            },
        ),
        migrations.CreateModel(
            name='JobStagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('stage_type', models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع مرحله')),
                ('planned_start_date', models.DateField(verbose_name='تاریخ شروع برنامه\u200cریزی شده')),
                ('planned_end_date', models.DateField(verbose_name='تاریخ پایان برنامه\u200cریزی شده')),
                ('sla_days', models.PositiveIntegerField(verbose_name='تعداد روز کار SLA')),
                ('capacity_shifted', models.BooleanField(default=False, verbose_name='جابجا شده به دلیل ظرفیت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_plans', to='recruitment_planning.jobrecruitmentplan', verbose_name='برنامه جذب')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_states', to='jobs.jobopportunitystage', verbose_name='مرحله ارزیابی')),
            ],
            options={
                'verbose_name': 'برنامه مرحله جذب',
                'verbose_name_plural': 'برنامه\u200cهای مراحل جذب',
                'ordering': ['stage__sequence'],
            },
        ),
    ]
