# Generated by Django 5.2.15 on 2026-06-04 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_workflowtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='فایل رزومه')),
            ],
            options={
                'verbose_name': 'متقاضی',
                'verbose_name_plural': 'متقاضیان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('degree', models.CharField(choices=[('ASSOCIATE', 'کاردانی'), ('BACHELOR', 'کارشناسی'), ('MASTER', 'کارشناسی ارشد'), ('PHD', 'دکتری')], max_length=20, verbose_name='مقطع تحصیلی')),
                ('major', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('university', models.CharField(max_length=100, verbose_name='دانشگاه / موسسه')),
                ('gpa', models.FloatField(verbose_name='معدل')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='سال فارغ\u200cالتحصیلی')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidates.candidate', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی متقاضی',
                'verbose_name_plural': 'سوابق تحصیلی متقاضیان',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('company', models.CharField(max_length=100, verbose_name='نام شرکت / سازمان')),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='شرح مسئولیت\u200cها و دستاوردها')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='candidates.candidate', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'سابقه کاری متقاضی',
                'verbose_name_plural': 'سوابق کاری متقاضیان',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'در حال بررسی / ارزیابی'), ('SELECTED', 'پذیرفته شده نهایی'), ('RESERVE', 'ذخیره'), ('REJECTED', 'رد شده')], default='IN_PROGRESS', max_length=20, verbose_name='وضعیت نهایی درخواست')),
                ('final_score', models.FloatField(default=0.0, verbose_name='امتیاز کل محاسبه شده')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate', verbose_name='متقاضی')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_applications', to='jobs.jobopportunitystage', verbose_name='مرحله فعلی ارزیابی')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobopportunity', verbose_name='فرصت شغلی')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار ارزیابی'), ('COMPLETED', 'قبول شده در این مرحله'), ('FAILED', 'مردود شده در این مرحله')], default='PENDING', max_length=20, verbose_name='وضعیت مرحله')),
                ('score', models.FloatField(default=0.0, verbose_name='امتیاز کسب شده')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات ارزیاب')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_stages', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده نمره')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_states', to='jobs.jobopportunitystage', verbose_name='مرحله ارزیابی شغل')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_states', to='candidates.jobapplication', verbose_name='درخواست همکاری')),
            ],
            options={
                'verbose_name': 'وضعیت مرحله ارزیابی متقاضی',
                'verbose_name_plural': 'وضعیت\u200cهای مراحل ارزیابی متقاضیان',
                'ordering': ['stage__sequence'],
                'unique_together': {('application', 'stage')},
            },
        ),
    ]
