# Generated by Django 5.2.15 on 2026-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='personnel_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره پرسنلی'),
        ),
    ]
