# Generated by Django 5.2.15 on 2026-06-04 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidatecertificate_candidatelanguage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('score', models.FloatField(default=0.0, verbose_name='نمره ثبت شده')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار ارزیابی'), ('COMPLETED', 'قبول شده در این مرحله'), ('FAILED', 'مردود شده در این مرحله')], default='PENDING', max_length=20, verbose_name='وضعیت مرحله')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات مصاحبه\u200cگر')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to=settings.AUTH_USER_MODEL, verbose_name='مصاحبه\u200cگر')),
                ('stage_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_scores', to='candidates.applicationstagestate', verbose_name='وضعیت مرحله')),
            ],
            options={
                'verbose_name': 'نمره مصاحبه\u200cگر',
                'verbose_name_plural': 'نمرات مصاحبه\u200cگران',
                'unique_together': {('stage_state', 'interviewer')},
            },
        ),
    ]
