# Generated by Django 5.2.15 on 2026-06-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_applicationstagestate_score_discrepancy_alert'),
        ('jobs', '0006_assessmentcompetency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorCompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('score', models.FloatField(default=0.0, verbose_name='نمره')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to='jobs.assessmentcompetency', verbose_name='شایستگی')),
                ('interviewer_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='candidates.interviewerscore', verbose_name='نمره مصاحبه\u200cگر')),
            ],
            options={
                'verbose_name': 'نمره شایستگی ارزیاب',
                'verbose_name_plural': 'سوابق نمرات شایستگی کانون',
                'unique_together': {('interviewer_score', 'competency')},
            },
        ),
    ]
