# Generated by Django 5.2.15 on 2026-06-04 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_workflowtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStageInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='وزن نمره مصاحبه\u200cگر (٪)')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='گروه / کمیته مصاحبه')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_interviewers', to='jobs.jobopportunity', verbose_name='فرصت شغلی')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='jobs.jobopportunitystage', verbose_name='مرحله ارزیابی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL, verbose_name='مصاحبه\u200cگر')),
            ],
            options={
                'verbose_name': 'مصاحبه\u200cگر مرحله ارزیابی',
                'verbose_name_plural': 'مصاحبه\u200cگران مراحل ارزیابی',
                'unique_together': {('stage', 'user')},
            },
        ),
    ]
