# Generated by Django 5.2.15 on 2026-06-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobstageinterviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunitystage',
            name='passing_score',
            field=models.FloatField(default=60.0, verbose_name='کف نمره قبولی'),
        ),
    ]
