# Generated by Django 5.2.15 on 2026-06-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobopportunitystage_passing_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام شایستگی')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='وزن شایستگی (٪)')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='jobs.jobopportunitystage', verbose_name='مرحله ارزیابی')),
            ],
            options={
                'verbose_name': 'شایستگی کانون ارزیابی',
                'verbose_name_plural': 'شایستگی\u200cهای کانون ارزیابی',
                'unique_together': {('stage', 'name')},
            },
        ),
    ]
