# Generated by Django 5.2.15 on 2026-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_assessmentcompetency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'دریافت شده'), ('PLANNING', 'برنامه\u200cریزی'), ('PUBLISHED', 'منتشر شده'), ('REGISTRATION_CLOSED', 'خاتمه ثبت\u200cنام'), ('SCREENING', 'غربالگری اولیه'), ('EXAM', 'آزمون کتبی'), ('INTERVIEW', 'مصاحبه حضوری'), ('ASSESSMENT', 'کانون ارزیابی'), ('FINAL_SELECTION', 'انتخاب نهایی'), ('CLOSED', 'اتمام یافته'), ('CANCELLED', 'لغو شده')], default='RECEIVED', max_length=30, verbose_name='وضعیت فرصت شغلی'),
        ),
    ]
