# Generated by Django 5.2.15 on 2026-06-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobopportunity_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='شرایط احراز'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='description',
            field=models.TextField(verbose_name='شرح شغل'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='job_category',
            field=models.CharField(blank=True, choices=[('اپراتور', 'اپراتور'), ('تعمیرکار', 'تعمیرکار'), ('کاردان', 'کاردان'), ('کاردان مسئول', 'کاردان مسئول'), ('کارشناس', 'کارشناس'), ('کارشناس مسئول', 'کارشناس مسئول'), ('کارشناس مدیریت', 'کارشناس مدیریت')], max_length=100, null=True, verbose_name='رده شغلی'),
        ),
    ]
