# Generated by Django 5.2.15 on 2026-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobopportunity_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunitystage',
            name='stage_type',
            field=models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع مرحله'),
        ),
        migrations.AddField(
            model_name='workflowstagetemplate',
            name='stage_type',
            field=models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع مرحله'),
        ),
    ]
