# Generated by Django 5.2.15 on 2026-06-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobopportunitycompetency_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API')),
                ('base_url', models.CharField(default='https://api.avalai.ir/v1', max_length=255, verbose_name='آدرس پایه (Base URL)')),
                ('model_name', models.CharField(default='gpt-4o', max_length=100, verbose_name='نام مدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات هوش مصنوعی',
                'verbose_name_plural': 'تنظیمات هوش مصنوعی',
            },
        ),
    ]
