# Generated by Django 5.2.15 on 2026-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_aisetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPostRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('post_code', models.CharField(max_length=50, verbose_name='کد پست سازمانی')),
                ('opt_advice', models.JSONField(blank=True, null=True, verbose_name='توصیه\u200cهای بهینه\u200cسازی شایستگی\u200cها')),
                ('scenario', models.TextField(blank=True, null=True, verbose_name='سناریوی ارزیابی کانون ارزیابی')),
                ('questions', models.JSONField(blank=True, null=True, verbose_name='سوالات مصاحبه ساختاریافته')),
                ('last_generated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تولید پاسخ')),
            ],
            options={
                'verbose_name': 'پیشنهاد هوش مصنوعی پست',
                'verbose_name_plural': 'پیشنهادات هوش مصنوعی پست\u200cها',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('post_code',), name='unique_post_code_active_recommendation')],
            },
        ),
    ]
