# Generated by Django 5.2.15 on 2026-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_aipostrecommendation_benchmark_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(default='سامانه جذب و استخدام پیجو', max_length=200, verbose_name='نام سازمان')),
                ('logo', models.FileField(blank=True, null=True, upload_to='org_logos/', verbose_name='لوگوی سازمان')),
            ],
            options={
                'verbose_name': 'تنظیمات سازمان',
                'verbose_name_plural': 'تنظیمات سازمان',
            },
        ),
    ]
