# Generated by Django 5.2.15 on 2026-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_organizationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_email_body',
            field=models.TextField(default='<div dir="rtl" style="font-family: Tahoma, Arial, sans-serif; text-align: right; padding: 20px; line-height: 1.6; color: #1e293b;">\n    <h2 style="color: #4f46e5;">دعوت به آزمون کتبی / تخصصی</h2>\n    <p>متقاضی گرامی <strong>{{ candidate_name }}</strong> عزیز، سلام؛</p>\n    <p>پس از بررسی اولیه رزومه شما برای فرصت شغلی <strong>«{{ job_title }}»</strong>، بدین\u200cوسیله از شما جهت شرکت در مرحله **آزمون تخصصی** دعوت به عمل می\u200cآید.</p>\n    <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; border-right: 4px solid #f59e0b; margin: 20px 0;">\n        <strong>جزییات برگزاری آزمون:</strong>\n        <ul>\n            <li><strong>تاریخ برگزاری:</strong> {{ date }}</li>\n            <li><strong>ساعت شروع:</strong> {{ time }}</li>\n            <li><strong>مدت زمان آزمون:</strong> ۹۰ دقیقه</li>\n            <li><strong>نوع آزمون:</strong> آنلاین (تستی و تشریحی)</li>\n        </ul>\n        <a href="{{ link }}" style="display: inline-block; margin-top: 10px; background-color: #4f46e5; color: #ffffff; padding: 8px 16px; text-decoration: none; border-radius: 6px;">ورود به سامانه آزمون آنلاین</a>\n    </div>\n    <p style="color: #ef4444; font-weight: bold;">⚠️ نکته مهم: لینک فوق فقط در بازه زمانی اعلام شده فعال خواهد بود.</p>\n    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>\n    <small style="color: #64748b;">تیم جذب و استخدام {{ company_name }}</small>\n</div>', verbose_name='متن ایمیل دعوت به آزمون (HTML)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_email_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال ایمیل دعوت به آزمون فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_email_subject',
            field=models.CharField(default='دعوت به آزمون کتبی / تخصصی', max_length=255, verbose_name='موضوع ایمیل دعوت به آزمون'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_sms_body',
            field=models.TextField(default='متقاضی گرامی {{ candidate_name }}، دعوت\u200cنامه شرکت در آزمون کتبی شغل "{{ job_title }}" برای شما صادر شد.\nزمان آزمون: {{ date }} ساعت {{ time }}\nجزییات بیشتر و لینک شرکت در آزمون در ایمیل شما و پنل پیجو:\n{{ link }}', verbose_name='متن پیامک دعوت به آزمون'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال پیامک دعوت به آزمون فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='interview_email_body',
            field=models.TextField(default='<div dir="rtl" style="font-family: Tahoma, Arial, sans-serif; text-align: right; padding: 20px; line-height: 1.6; color: #1e293b;">\n    <h2 style="color: #4f46e5;">دعوت به جلسه مصاحبه تخصصی</h2>\n    <p>جناب/سرکار خانم <strong>{{ candidate_name }}</strong> عزیز، سلام؛</p>\n    <p>با توجه به نتایج مثبت ارزیابی\u200cهای قبلی شما برای فرصت شغلی <strong>«{{ job_title }}»</strong>، از شما دعوت می\u200cشود در جلسه مصاحبه با تیم فنی و مدیران ارشد شرکت نمایید.</p>\n    <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; border-right: 4px solid #10b981; margin: 20px 0;">\n        <strong>مشخصات جلسه مصاحبه:</strong>\n        <ul>\n            <li><strong>تاریخ مصاحبه:</strong> {{ date }}</li>\n            <li><strong>ساعت برگزاری:</strong> {{ time }}</li>\n            <li><strong>نوع جلسه:</strong> آنلاین (تصویری)</li>\n            <li><strong>لینک ورود به اتاق جلسه:</strong> <a href="{{ link }}">{{ link }}</a></li>\n        </ul>\n    </div>\n    <p>پیشنهاد می\u200cشود ۱۰ دقیقه قبل از ساعت مقرر، اتصالات سیستم خود (دوربین و میکروفون) را بررسی نمایید. در صورت نیاز به هماهنگی مجدد با ایمیل یا شماره تماس کارشناس جذب مربوطه تماس حاصل فرمایید.</p>\n    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>\n    <small style="color: #64748b;">تیم جذب و استخدام {{ company_name }}</small>\n</div>', verbose_name='متن ایمیل دعوت به مصاحبه (HTML)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='interview_email_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال ایمیل دعوت به مصاحبه فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='interview_email_subject',
            field=models.CharField(default='دعوت به جلسه مصاحبه تخصصی', max_length=255, verbose_name='موضوع ایمیل دعوت به مصاحبه'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='interview_sms_body',
            field=models.TextField(default='جناب/سرکار خانم {{ candidate_name }}، جلسه مصاحبه شما برای موقعیت شغلی "{{ job_title }}" تنظیم شد.\nزمان: {{ date }} ساعت {{ time }}\nجزییات و لینک اتصال آنلاین (یا لوکیشن حضوری) به ایمیل شما ارسال شد.\n{{ company_name }}', verbose_name='متن پیامک دعوت به مصاحبه'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='interview_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال پیامک دعوت به مصاحبه فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='offer_email_body',
            field=models.TextField(default='<div dir="rtl" style="font-family: Tahoma, Arial, sans-serif; text-align: right; padding: 20px; line-height: 1.6; color: #1e293b;">\n    <h2 style="color: #10b981;">🎉 تبریک! پذیرش نهایی و پیشنهاد همکاری در {{ company_name }}</h2>\n    <p>همکار آینده ما، جناب/سرکار خانم <strong>{{ candidate_name }}</strong> عزیز، سلام؛</p>\n    <p>بسیار خرسندیم که به اطلاع شما برسانیم فرآیند ارزیابی\u200cهای شما با موفقیت کامل سپری شده و شایستگی شما برای احراز فرصت شغلی <strong>«{{ job_title }}»</strong> مورد تایید نهایی قرار گرفته است.</p>\n    <p>ما مشتاقانه منتظر پیوستن شما به تیم پویای <strong>{{ company_name }}</strong> هستیم.</p>\n    <div style="background-color: #f0fdf4; padding: 15px; border-radius: 8px; border: 1px solid #bbf7d0; margin: 20px 0;">\n        <strong>گام بعدی چیست؟</strong><br/>\n        پیش\u200cنویس تفاهم\u200cنامه و آفر فرم همکاری (شامل جزییات حقوق، بیمه، ساعات کاری و مزایا) پیوست این ایمیل شده و در پنل شما قرار گرفته است. خواهشمند است حداکثر تا تاریخ {{ date }} فرم امضا شده را از طریق لینک زیر برای ما ارسال نمایید.<br/>\n        <a href="{{ link }}" style="display: inline-block; margin-top: 10px; background-color: #10b981; color: #ffffff; padding: 8px 16px; text-decoration: none; border-radius: 6px; font-weight: bold;">بررسی و امضای پیشنهاد همکاری</a>\n    </div>\n    <p>در صورت وجود هرگونه ابهام یا سوال، کارشناس جذب ما <strong>{{ recruiter_name }}</strong> آماده پاسخگویی به شماست.</p>\n    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>\n    <small style="color: #64748b;">مدیریت منابع انسانی {{ company_name }}</small>\n</div>', verbose_name='متن ایمیل پیشنهاد همکاری (HTML)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='offer_email_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال ایمیل پیشنهاد همکاری فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='offer_email_subject',
            field=models.CharField(default='🎉 تبریک! پذیرش نهایی و پیشنهاد همکاری در {{ company_name }}', max_length=255, verbose_name='موضوع ایمیل پیشنهاد همکاری'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='offer_sms_body',
            field=models.TextField(default='تبریک فراوان {{ candidate_name }} عزیز! 🎉\nشما در فرآیند جذب "{{ job_title }}" پذیرفته شدید.\nآفر فرم (پیشنهاد همکاری) به ایمیل شما ارسال شد. لطفا نسبت به بررسی و امضای آن اقدام کنید:\n{{ link }}\n{{ company_name }}', verbose_name='متن پیامک پیشنهاد همکاری'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='offer_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال پیامک پیشنهاد همکاری فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reg_email_body',
            field=models.TextField(default='<div dir="rtl" style="font-family: Tahoma, Arial, sans-serif; text-align: right; padding: 20px; line-height: 1.6; color: #1e293b;">\n    <h2 style="color: #4f46e5;">دریافت رزومه با موفقیت انجام شد</h2>\n    <p>جناب/سرکار خانم <strong>{{ candidate_name }}</strong> عزیز، سلام؛</p>\n    <p>از علاقه\u200cمندی شما به همکاری با <strong>{{ company_name }}</strong> سپاسگزاریم.</p>\n    <p>رزومه شما برای فرصت شغلی <strong>«{{ job_title }}»</strong> دریافت گردید و در حال حاضر در مرحله غربالگری اولیه قرار دارد.</p>\n    <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; border-right: 4px solid #4f46e5; margin: 20px 0;">\n        <strong>اطلاعات پیگیری وضعیت:</strong><br/>\n        برای مشاهده وضعیت لحظه\u200cای پرونده خود، دریافت بازخوردها و شرکت در آزمون\u200cهای آنلاین آتی، می\u200cتوانید به پنل اختصاصی متقاضیان مراجعه نمایید.<br/>\n        <a href="{{ link }}" style="display: inline-block; margin-top: 10px; background-color: #4f46e5; color: #ffffff; padding: 8px 16px; text-decoration: none; border-radius: 6px;">ورود به پنل متقاضی</a>\n    </div>\n    <p>در صورت تایید رزومه شما، مراحل بعدی از طریق پیامک و ایمیل اطلاع\u200cرسانی خواهد شد.</p>\n    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>\n    <small style="color: #64748b;">تیم جذب و استخدام {{ company_name }}</small>\n</div>', verbose_name='متن ایمیل ثبت\u200cنام (HTML)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reg_email_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال ایمیل ثبت\u200cنام فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reg_email_subject',
            field=models.CharField(default='دریافت رزومه با موفقیت انجام شد', max_length=255, verbose_name='موضوع ایمیل ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reg_sms_body',
            field=models.TextField(default='{{ candidate_name }} عزیز، رزومه شما برای شغل "{{ job_title }}" در {{ company_name }} دریافت شد.\nبرای پیگیری وضعیت و آزمون\u200cها به پنل خود مراجعه کنید:\n{{ link }}', verbose_name='متن پیامک ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reg_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال پیامک ثبت\u200cنام فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reject_email_body',
            field=models.TextField(default='<div dir="rtl" style="font-family: Tahoma, Arial, sans-serif; text-align: right; padding: 20px; line-height: 1.6; color: #1e293b;">\n    <h2 style="color: #ef4444;">تقدیر و تشکر از حضور در فرآیند ارزیابی</h2>\n    <p>جناب/سرکار خانم <strong>{{ candidate_name }}</strong> عزیز، سلام؛</p>\n    <p>از اینکه وقت گرانبهای خود را برای شرکت در فرآیند استخدام موقعیت شغلی <strong>«{{ job_title }}»</strong> در اختیار <strong>{{ company_name }}</strong> قرار دادید، صمیمانه سپاسگزاریم.</p>\n    <p>پس از بررسی\u200cهای دقیق و مصاحبه\u200cهای انجام شده با کاندیداهای محترم، متاسفانه در این دوره امکان پذیرش و همکاری با شما فراهم نگردید. انتخاب نهایی بر اساس تطابق حداکثری نیازهای فعلی تیم با سوابق فنی صورت گرفته و این به معنی نفی شایستگی\u200cهای ارزشمند شما نیست.</p>\n    <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; border-right: 4px solid #ef4444; margin: 20px 0;">\n        <strong>نگاهداشت رزومه در بانک استعدادها:</strong><br/>\n        سوابق ارزنده شما در بانک استعدادهای (Talent Pool) ما آرشیو می\u200cشود تا در صورت تعریف فرصت\u200cهای شغلی جدید و متناسب با تخصصتان، در اولویت تماس مجدد همکاران ما قرار بگیرید.\n    </div>\n    <p>برای شما در تمام مراحل زندگی حرفه\u200cای آرزوی موفقیت و پیروزی داریم.</p>\n    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>\n    <small style="color: #64748b;">تیم جذب و استخدام {{ company_name }}</small>\n</div>', verbose_name='متن ایمیل رد رزومه (HTML)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reject_email_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال ایمیل رد رزومه فعال باشد'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reject_email_subject',
            field=models.CharField(default='تقدیر و تشکر از حضور در فرآیند ارزیابی', max_length=255, verbose_name='موضوع ایمیل رد رزومه'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reject_sms_body',
            field=models.TextField(default='{{ candidate_name }} عزیز، از وقتی که برای ارزیابی شغل "{{ job_title }}" در {{ company_name }} گذاشتید سپاسگزاریم.\nمتاسفانه در این دوره امکان همکاری فراهم نشد. رزومه شما در بانک استعدادهای ما ذخیره می\u200cگردد.\nنامه رسمی و جزئیات بیشتر به ایمیل شما ارسال شد.', verbose_name='متن پیامک رد رزومه'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='reject_sms_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال پیامک رد رزومه فعال باشد'),
        ),
    ]
