# Generated by Django 5.2.16 on 2026-07-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_alter_jobopportunity_request_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobopportunity',
            name='unique_code_active',
        ),
    ]
